# Generated by Django 5.2.7 on 2025-10-25 22:58

from django.db import migrations
from django.utils import timezone


def create_sample_polls(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    Choice = apps.get_model('polls', 'Choice')
    
    # Create sample questions
    q1 = Question.objects.create(
        question_text="What's your favorite programming language?",
        pub_date=timezone.now()
    )
    q2 = Question.objects.create(
        question_text="Which framework do you prefer?",
        pub_date=timezone.now()
    )
    
    # Create choices for question 1
    Choice.objects.create(question=q1, choice_text="Python", votes=0)
    Choice.objects.create(question=q1, choice_text="JavaScript", votes=0)
    Choice.objects.create(question=q1, choice_text="Java", votes=0)
    
    # Create choices for question 2
    Choice.objects.create(question=q2, choice_text="Django", votes=0)
    Choice.objects.create(question=q2, choice_text="Flask", votes=0)
    Choice.objects.create(question=q2, choice_text="FastAPI", votes=0)


def reverse_sample_polls(apps, schema_editor):
    Question = apps.get_model('polls', 'Question')
    Question.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_polls, reverse_sample_polls),
    ]
